schemes:
  qaq: &qaq

  bright:
    red: '#c82829'
    orange: '#f5871f'
    yellow: '#eab700'
    green: '#719c00'
    aqua: '#3e999f'
    blue: '#4271ae'
    purple: '#8959a8'
    #cursor:
    #cursor: '#403f53'
    #text: '#fbfbfb'
  normal:
    red: '#c82829'
    orange: '#f5871f'
    yellow: '#eab700'
    green: '#718c00'
    aqua: '#3e999f'
    blue: '#4271ae'
    purple: '#8959a8'
  primary:
    background: '#ffffff'
    foreground: '#403f53'
  selection:
    background: '#f2f2f2'
    text: '#403f53'
